### get all product
GET http://localhost:3000/api/produk

### insert new product
POST http://localhost:3000/api/produk
Content-Type: application/json

{
    "name": "Mouse Gaming",
    "price":"300000",
    "description": "hyper sensitive mouse",
    "stock": 12
}

###